pull_request_rules:
  - name: automatic merge when CI passes, 1 review, and 1 label
    conditions:
      - base=master
      - label=merge
      - label!=blocked
      - label!=freeze
      - title~=^[fix|feat|chore|perf].*
    actions:
      merge:
        method: squash
        strict: smart
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
