language: node_js
node_js: '8.11.2'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
stages:
  - name: Test
    if: (type IN (pull_request))
  #- name: Bump Version
    #if: (type IN (push) AND branch = master)


jobs:
  include:
    - stage: Test
      script:
        - yarn lint
    - script:
        - travis_wait yarn test
        - travis_wait yarn codecov
    - stage: Bump Version
      script:
        - git config user.email ${GH_EMAIL}
        - git config user.name ${GH_USER}
        - git clone git://${GH_REPO}
        - git remote
        - git checkout develop
        - yarn bump
        - git push --follow-tags "https://${GH_TOKEN}@${GH_REPO}" develop
        - yarn gh-release --yes
