coverage:
  status:
    project:
      api:
        paths:
          - packages/apollos-church-api/*
          - packages/apollos-data-*/*
          - packages/apollos-config/*
          - packages/apollos-server-core/*
      mobile:
        paths:
          - packages/newspringchurchapp/*
          - packages/ui-kit/*
comment:
  layout: "reach, diff, files"
  behavior: once
