# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Detox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [10.19.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn

    - name: Install Cocoapods
      run: sudo gem install cocoapods -v 1.9.1

    - name: Install Dependencies
      run: yarn --ignore-scripts && yarn jetify && pods install --repo-update

    - name: Install Wix iOS Tools
      run: brew tap wix/brew && brew install applesimutils

    - name: Detox
      run: yarn e2e
